
=head1 Haml Whitespace Semantics Extension (WSE) Implementation Notes

  Draft v0.5002, 30 Oct 2010

=head2 Authors

  Proposer: Nick Ragouzis, Enosis Group

  Contributors:

=head2 Repo Moved

The wip-wse branch of enosis/text-haml has been cleaved and is now master at: http://github.com/enosis/haml-wse-specs.

This document is now found at: http://github.com/enosis/haml-wse-specs/blob/master/doc/Haml_WhitespaceSemanticsExtension_ImplementationNotes.pod.

